const db = require('../db')
const Card = require('../models/card')

db.on('error', console.error.bind(console, 'Cards - MongoDB connection error:'))

const main = async() => {
    const cards = [
        /////////////  Major Arcana  /////////////
        {
            // [0]
            name: '0. The Fool',
            number: '0',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: [
                'Neptune',
                'Uranus',
            ],
            planet_icon: [
                'neptune_icon.svg',
                'uranus_icon.svg',
            ],
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: 'https://images.squarespace-cdn.com/content/v1/6282048f3ddae806d695b4b8/2513a85e-30d5-4148-9939-3680e77bedd5/0-the-Fool.jpg?format=500w',
            up_key: [
                'new beginnings',
                'potential',
                'innocence',
                'joy',
                'freedom',
                'optimism',
                'spontaneity',
                'adventure',
            ],
            up_gen: '<upright description>',
            rev_img: 'https://images.squarespace-cdn.com/content/v1/6282048f3ddae806d695b4b8/987fe230-ad3f-4c9a-8385-6844ee8c7148/fool.jpg?format=500w',
            rev_key: [
                'inexperience',
                'risk',
                'foolishness',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [1]
            name: 'I. The Magician',
            number: '1',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Mercury',
            planet_icon: 'mercury_icon.svg',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'manifestations',
                'success',
                'resourcefulness',
                'will',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'trickery',
                'manipulation',
                'indecision',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [2]
            name: 'II. The High Priestess',
            number: '2',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Moon',
            planet_icon: 'moon_icon.svg',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'intuition',
                'mystery',
                'subconscious',
                'divine feminine',
                'duality',
                'wisdom',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'secrets',
                'disconnection',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [3]
            name: 'III. The Empress',
            number: '3',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Venus',
            planet_icon: 'venus_icon.svg',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'abundance',
                'nurturing',
                'femininity',
                'creativity',
                'fertility',
                'motherhood',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'insecurity',
                'dependence',
                'infertility',
                'creative blocks'
            ],
            rev_gen: '<revered description>',
        },
        {
            // [4]
            name: 'IV. The Emperor',
            number: '4',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Mars',
            planet_icon: 'mars_icon.svg',
            astro: 'Aries',
            astro_icon: 'aries_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'logic',
                'action',
                'structure',
                'patriarchy',
                'protection',
                'fatherhood',
                'maturity',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'stubbornness',
                'domineering',
                'recklessness',
                'unfocused',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [5]
            name: 'V. The Hierophant',
            number: '5',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Venus',
            planet_icon: 'venus_icon.svg',
            astro: 'Taurus',
            astro_icon: 'taurus_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'law',
                'tradition',
                'religion',
                'authority',
                'ethics',
                'morality',
                'teaching',
                'wholeness',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'freedom',
                'rebellion',
                'personal beliefs',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [6]
            name: 'VI. The Lovers',
            number: '6',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Mercury',
            planet_icon: 'mercury_icon.svg',
            astro: 'Gemini',
            astro_icon: 'gemini_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'love',
                'sexuality',
                'attraction',
                'relationships',
                'choices',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'self-love',
                'imbalance',
                'disharmony',
                'disconnection',
                'indecision',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [7]
            name: 'VII. The Chariot',
            number: '7',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Moon',
            planet_icon: 'moon_icon.svg',
            astro: 'Cancer',
            astro_icon: 'cancer_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'success',
                'self-discipline',
                'ambition',
                'action',
                'willpower',
                'movement',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'opposition',
                'directionless',
                'powerless',
                'stagnation',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [8]
            name: 'VIII. Strength',
            number: '8',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Sun',
            planet_icon: 'sun_icon.svg',
            astro: 'Leo',
            astro_icon: 'leo_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'strength',
                'bravery',
                'confidence',
                'self-control',
                'power',
                'patience',
                'balance',
                'compassion',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'self-doubt',
                'cowardice',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [9]
            name: 'IX. The Hermit',
            number: '9',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Mercury',
            planet_icon: 'mercury_icon.svg',
            astro: 'Virgo',
            astro_icon: 'virgo_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'solitude',
                'wisdom',
                'introspection',
                'self-examination',
                'enlightenment',
                'guidance',
                'meditation',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'loneliness',
                'isolation',
                'withdrawal',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [10]
            name: 'X. The Wheel of Fortune',
            number: '10',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Jupiter',
            planet_icon: 'jupiter_icon.svg',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'change',
                'cycles',
                'karma',
                'destiny',
                'good fortune',
                'turning point',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'resistance to change',
                'bad luck',
                'misfortune',
                'delays'
            ],
            rev_gen: '<revered description>',
        },
        {
            // [11]
            name: 'XI. Justice',
            number: '11',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Venus',
            planet_icon: 'venus_icon.svg',
            astro: 'Libra',
            astro_icon: 'libra_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'justice',
                'truth',
                'consequences',
                'accountability',
                'fairness',
                'law',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'injustice',
                'dishonesty',
                'corruption',
                'bias',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [12]
            name: 'XII. The Hanged Man',
            number: '12',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Neptune',
            planet_icon: 'neptune_icon.svg',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'contemplation',
                'waiting',
                'surrender',
                'perspective',
                'limbo',
                'transition',
                'sacrifice',
                'transformation',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'stagnation',
                'delays',
                'indecision',
                'fear of letting go',
                'victim mindset',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [13]
            name: 'XIII. Death',
            number: '13',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Pluto',
            planet_icon: 'pluto_icon.svg',
            astro: 'Scorpio',
            astro_icon: 'scorpio_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'change',
                'endings',
                'new beginnings',
                'transformation',
                'renewal',
                'inevitability',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'fear of change',
                'decay',
                'lethargy',
                'hopelessness',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [14]
            name: 'XIV. Temperance',
            number: '14',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Jupiter',
            planet_icon: 'jupiter_icon.svg',
            astro: 'Sagittarius',
            astro_icon: 'sagittarius_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'balance',
                'serenity',
                'patience',
                'moderation',
                'peace',
                'blending',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'imbalance',
                'excess',
                'discord',
                'disharmony',
                'overindulgence',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [15]
            name: 'XV. The Devil',
            number: '15',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Saturn',
            planet_icon: 'saturn_icon.svg',
            astro: 'Capricorn',
            astro_icon: 'capricorn_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'control',
                'temptation',
                'addiction',
                'excess',
                'materialism',
                'negativity',
                'deviance',
                'shadow side',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'freedom',
                'independence',
                'release',
                'personal power',
                'detachment',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [16]
            name: 'XVI. The Tower',
            number: '16',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Mars',
            planet_icon: 'mars_icon.svg',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'chaos',
                'calamity',
                'disaster',
                'destruction',
                'revolution',
                'disruption',
                'rebuilding',
                'unexpected',
                'awakening',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'averting disaster',
                'transformation',
                'revelation',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [17]
            name: 'XVII. The Star',
            number: '17',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Uranus',
            planet_icon: 'uranus_icon.svg',
            astro: 'Aquarius',
            astro_icon: 'aquarius_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'hope',
                'inspiration',
                'healing',
                'optimism',
                'faith',
                'rejuvenation',
                'peace',
                'manifestation',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'despair',
                'disconnection',
                'lack of faith',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [18]
            name: 'XVIII. The Moon',
            number: '18',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: [
                'Moon',
                'Neptune',
            ],
            planet_icon: [
                'moon_icon.svg',
                'neptune_icon.svg',
            ],
            astro: 'Pisces',
            astro_icon: 'pisces_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'illusion',
                'intuition',
                'subconscious',
                'secrets',
                'deception',
                'dreams',
                'uncertainty',
                'duality',
                'fear',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'clarity',
                'secrets exposed',
                'releasing fear',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [19]
            name: 'XIX. The Sun',
            number: '19',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Sun',
            planet_icon: 'sun_icon.svg',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'joy',
                'happiness',
                'abundance',
                'success',
                'optimism',
                'vitality',
                'confidence',
                'inner child',
                'fun',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'pessimism',
                'overenthusiastic',
                'conceit',
                'depression',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [20]
            name: 'XX. Judgement',
            number: '20',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Pluto',
            planet_icon: 'pluto_icon.svg',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'judgement',
                'purpose',
                'rebirth',
                'awakening',
                'absolution',
                'passage',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'self-doubt',
                'self-deprecation',
                'misjudgement',
                'false accusations',
                'unwillingless to learn from the past'
            ],
            rev_gen: '<revered description>',
        },
        {
            // [21]
            name: 'XXI. The World',
            number: '21',
            suit: 'Major Arcana',
            suit_icon: 'assets/icons-elements/major.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Saturn',
            planet_icon: 'saturn_icon.svg',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'completion',
                'possibility',
                'accomplishment',
                'equality',
                'connection',
                'travel',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'incompletion',
                'delays',
                'unfinishsed business',
            ],
            rev_gen: '<revered description>',
        },
        

        /////////////    Wands    /////////////
        {
            // [22]
            name: 'Ace of Wands',
            number: '1',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Aries',
                'Leo',
                'Sagittarius'
            ],
            astro_icon: [
                'aries_icon.svg',
                'leo_icon.svg',
                'sagittarius_icon.svg'
            ],
            // symbolism: 'OPTIONAL',
            // meaning: 'OPTIONAL',
            up_img: '<upright image URL>',
            up_key: [
                'beginning',
                'creation',
                'inspiration',
                'passion',
                'energy',
                'new project',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'creative blocks',
                'lethargy',
                'uninspired',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [23]
            name: 'Two of Wands',
            number: '2',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Mars>',
            planet_icon: 'mars_icon.svg',
            astro: 'Aries',
            astro_icon: 'aries_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'planning',
                'vision',
                'control',
                'discovery',
                'progress',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'comfort zone',
                'powerlessness',
                'disruption',
                'lack of planning',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [24]
            name: 'Three of Wands',
            number: '3',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Sun',
            planet_icon: 'sun_icon.svg',
            astro: 'Aries',
            astro_icon: 'aries_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'expansion',
                'adventure',
                'foresight',
                'opportunity',
                'travel',
                'confidence',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'setbacks',
                'limitations',
                'obstacles',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [25]
            name: 'Four of Wands',
            number: '4',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Venus',
            planet_icon: 'venus_icon.svg',
            astro: 'Aries',
            astro_icon: 'aries_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'celebration',
                'bliss',
                'harmony',
                'foundations',
                'home',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'transition',
                'personal celebration',
                'instability',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [26]
            name: 'Five of Wands',
            number: '5',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Saturn',
            planet_icon: 'saturn_icon.svg',
            astro: 'Leo',
            astro_icon: 'leo_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'competition',
                'conflict',
                'disagreements',
                'strife',
                'tension',
                'assertiveness',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'peace',
                'truce',
                'agreements',
                'escalation',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [27]
            name: 'Six of Wands',
            number: '6',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Jupiter',
            planet_icon: 'jupiter_icon.svg',
            astro: 'Leo',
            astro_icon: 'leo_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'victory',
                'success',
                'winning',
                'recognition',
                'confidence',
                'awards',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'self-doubt',
                'fall from grace',
                'losing',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [28]
            name: 'Seven of Wands',
            number: '7',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Mars',
            planet_icon: 'mars_icon.svg',
            astro: 'Leo',
            astro_icon: 'leo_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'challenge',
                'tenacity',
                'conviction',
                'defense',
                'opposition',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'resolution',
                'giving up',
                'overwhelm',
                'exhaustion',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [29]
            name: 'Eight of Wands',
            number: '8',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Mercury',
            planet_icon: 'mercury_icon.svg>',
            astro: 'Sagittarius',
            astro_icon: 'sagittarius_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'speed',
                'movement',
                'rapid change',
                'action',
                'travel by air',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'frustration',
                'waiting',
                'procrastination',
                'patience',
                'slow pace',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [30]
            name: 'Nine of Wands',
            number: '9',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Moon',
            planet_icon: 'moon_icon.svg',
            astro: 'Sagittarius',
            astro_icon: 'sagittarius_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'perserverance',
                'resilience',
                'determination',
                'boundaries',
                'hope',
                'exhaustion',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'defensiveness',
                'stubbornness',
                'distrust',
                'paranoia',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [31]
            name: 'Ten of Wands',
            number: '10',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            planet: 'Saturn',
            planet_icon: 'saturn_icon.svg',
            astro: 'Sagittarius',
            astro_icon: 'sagittarius_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'accomplishment',
                'success',
                'responsibility',
                'burden',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'burnout',
                'breakdown',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [32]
            name: 'Page of Wands',
            number: '11',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: [
                'Fire',
                'Earth'
            ],
            element_icon: [
                'fire_icon.svg',
                'earth_icon.svg'
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'inspiration',
                'vitality',
                'exploration',
                'potential',
                'ideas',
                'creativity',
                'education',
                'good news',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'unimaginative',
                'lazy',
                'rebellious',
                'bad news',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [33]
            name: 'Knight of Wands',
            number: '12',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: 'Fire',
            element_icon: 'fire_icon.svg',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Sagittarius',
                'Scorpio',
            ],
            astro_icon: [
                'sagittarius_icon.svg',
                'scorpio_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'passion',
                'fearlessness',
                'enthusiasm',
                'adventure',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'impulsiveness',
                'recklessness',
                'arrogance',
                'passivity',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [34]
            name: 'Queen of Wands',
            number: '13',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: [
                'Fire',
                'Water',
            ],
            element_icon: [
                'fire_icon.svg',
                'water_icon.svg',
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Pisces',
                'Aries',
            ],
            astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'confidence',
                'vivaciousness',
                'charisma',
                'creativity',
                'sociability',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'introversion',
                'lack of self-confidence',
                'jealousy',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [35]
            name: 'King of Wands',
            number: '14',
            suit: 'Wands',
            suit_icon: 'wand_icon.svg',
            element: [
                'Fire',
                'Air',
            ],
            element_icon: [
                'fire_icon.svg',
                'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Leo',
                'Cancer'
            ],
            astro_icon: [
                'leo_icon.svg',
                'cancer_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'leadership',
                'mastermind',
                'visionary',
                'innovation',
                'dynamic',
                'power',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'dictator',
                'hot-tempered',
                'ineffective',
            ],
            rev_gen: '<revered description>',
        },


        /////////////    Swords    /////////////
        {
            // [36]
            name: 'Ace of Swords',
            number: '1',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Gemini',
                'Libra',
                'Aquarius',
            ],
            astro_icon: [
                'gemini_icon.svg',
                'libra_icon.svg',
                'aquarius_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'clarity',
                'epiphany',
                'truth',
                'new ideas',
                'opportunity',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'overthinking',
                'confusion',
                'irrationality'
            ],
            rev_gen: '<revered description>',
        },
        {
            // [37]
            name: 'Two of Swords',
            number: '2',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Moon',
            planet_icon: 'moon_icon.svg',
            astro: 'Libra',
            astro_icon: 'libra_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'balance',
                'contemplation',
                'difficult decisions',
                'clarity',
                'denial',
                'stress',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'indecision',
                'avoidance',
                'stalemate',
                'clarity',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [38]
            name: 'Three of Swords',
            number: '3',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Saturn',
            planet_icon: 'saturn_icon.svg',
            astro: 'Libra',
            astro_icon: 'libra_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'heartbreak',
                'sorrow',
                'depression',
                'breakup',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'self-deprecation',
                'optimism',
                'recovery',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [39]
            name: 'Four of Swords',
            number: '4',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Jupiter',
            planet_icon: 'jupiter_icon.svg',
            astro: 'Libra',
            astro_icon: 'libra_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'rest',
                'rejuvenation',
                'retreat',
                'contemplation',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'stress',
                'exhaustion',
                'anxiety',
                'restlessness'
            ],
            rev_gen: '<revered description>',
        },
        {
            // [40]
            name: 'Five of Swords',
            number: '5',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Venus',
            planet_icon: 'venus_icon.svg',
            astro: 'Aquarius',
            astro_icon: 'aquarius_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'competition',
                'aggression',
                'discord',
                'defeat',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'reconciliation',
                'truce',
                'peace',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [41]
            name: 'Six of Swords',
            number: '6',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Mercury',
            planet_icon: 'mercury_icon.svg',
            astro: 'Aquarius',
            astro_icon: 'aquarius_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'transition',
                'release',
                'moving on',
                'healing',
                'calm',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'stuck',
                'stagnation',
                'escapsism',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [42]
            name: 'Seven of Swords',
            number: '7',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Moon',
            planet_icon: 'moon_icon.svg',
            astro: 'Aquarius',
            astro_icon: 'aquarius_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'deception',
                'dishonesty',
                'cunning',
                'trickery',
                'theft',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'confessions',
                'secrets',
                'truth',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [43]
            name: 'Eight of Swords',
            number: '8',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Jupiter',
            planet_icon: 'jupiter_icon.svg',
            astro: 'Gemini',
            astro_icon: 'gemini_icon.svg>',
            up_img: '<upright image URL>',
            up_key: [
                'negativity',
                'restriction',
                'helplessness',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'freedom',
                'empowerment',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [44]
            name: 'Nine of Swords',
            number: '9',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Mars',
            planet_icon: 'mars_icon.svg',
            astro: 'Gemini',
            astro_icon: 'gemini_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'nightmares',
                'anxiety',
                'anguish',
                'worry',
                'despair',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'recovery',
                'solace',
                'hope',
                'overcoming',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [45]
            name: 'Ten of Swords',
            number: '10',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            planet: 'Sun',
            planet_icon: 'sun_icon.svg',
            astro: 'Gemini',
            astro_icon: 'gemini_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'betrayal',
                'pain',
                'endings',
                'drama',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'resistance',
                'regeneration',
                'perserverance',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [46]
            name: 'Page of Swords',
            number: '11',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: [
                'Air',
                'Earth',
            ],
            element_icon: [
                'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
                'earth_icon.svg'
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'ideas',
                'truth',
                'communication',
                'enthusiasm',
                'curiosity',
                'learning',
                'good news',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'unproductive',
                'miscommunication',
                'lies',
                'bad news',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [47]
            name: 'Knight of Swords',
            number: '12',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: [
                'Air',
                'Fire',
            ],
            element_icon: [
                'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
                'fire_icon.svg',
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Gemini',
                'Taurus'
            ],
            astro_icon: [
                'gemini_icon.svg',
                'taurus_icon.svg'
            ],
            up_img: '<upright image URL>',
            up_key: [
                'courage',
                'tenacity',
                'drive',
                'focus',
                'action',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'laziness',
                'inaction',
                'restless mind',
                'lack of focus',

            ],
            rev_gen: '<revered description>',
        },
        {
            // [48]
            name: 'Queen of Swords',
            number: '13',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Air',
                'Water',
            ],
            astro_icon: [
                'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
                'water_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'wisdom',
                'logic',
                'straightforward',
                'independence',
                'communication',
                'sharp wit',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'critical',
                'overly emotional',
                'cold-hearted'
            ],
            rev_gen: '<revered description>',
        },
        {
            // [49]
            name: 'King of Swords',
            number: '14',
            suit: 'Swords',
            suit_icon: 'sword_icon.svg',
            element: 'Air',
            element_icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Aquarius',
                'Capricorn',
            ],
            astro_icon: [
                'aquarius_icon.svg',
                'capricorn_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'intellectual',
                'logic',
                'genius',
                'truth',
                'communication',
                'uncompromising',
                'fairness',
                'action without emotion',
                'power',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'cruelty',
                'abuse of power',
            ],
            rev_gen: '<revered description>',
        },


        /////////////    Cups    /////////////
        {
            // [50]
            name: 'Ace of Cups',
            number: '1',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Cancer',
                'Scorpio',
                'Pisces',
            ],
            astro_icon: [
                'cancer_icon.svg',
                'scorpio_icon.svg',
                'pisces_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'love',
                'romance',
                'abundance',
                'creativity',
                'intuition',
                'gift',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'rejection',
                'loss of love',
                'repressed emotions'
            ],
            rev_gen: '<revered description>',
        },
        {
            // [51]
            name: 'Two of Cups',
            number: '2',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Venus',
            planet_icon: 'venus_icon.svg',
            astro: 'Cancer',
            astro_icon: 'cancer_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'love',
                'harmony',
                'emotional balance',
                'compromise',
                'truce',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'division',
                'separation',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [52]
            name: 'Three of Cups',
            number: '3',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Mercury',
            planet_icon: 'mercury_icon.svg',
            astro: 'Cancer',
            astro_icon: 'cancer_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'celebration',
                'friendship',
                'community',
                'joy',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'antisocial',
                'gossip',
                'overindulgence',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [53]
            name: 'Four of Cups',
            number: '4',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Moon',
            planet_icon: 'moon_icon.svg',
            astro: 'Cancer',
            astro_icon: 'cancer_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'contemplation',
                'selectiveness',
                'boredom',
                'apathy',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'depression',
                'realignment',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [54]
            name: 'Five of Cups',
            number: '5',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Mars',
            planet_icon: 'mars_icon.svg',
            astro: 'Scorpio',
            astro_icon: 'scorpio_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'hopelessness',
                'disappointment',
                'loss',
                'grief',
                'pessimism',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'peace',
                'gratitude',
                'optimism',
                'healing',
                'acceptance'
            ],
            rev_gen: '<revered description>',
        },
        {
            // [55]
            name: 'Six of Cups',
            number: '6',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Sun',
            planet_icon: 'sun_icon.svg',
            astro: 'Scorpio',
            astro_icon: 'scorpio_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'innocence',
                'joy',
                'childhood',
                'friendship',
                'family',
                'generosity',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'inner child',
                'the past',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [56]
            name: 'Seven of Cups',
            number: '7',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Venus',
            planet_icon: 'venus_icon.svg',
            astro: 'Scorpio',
            astro_icon: 'scorpio_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'options',
                'decisions',
                'illusion',
                'imagination',
                'fantasy',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'overwhelm',
                'clarity',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [57]
            name: 'Eight of Cups',
            number: '8',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Saturn',
            planet_icon: 'saturn_icon.svg',
            astro: 'Pisces',
            astro_icon: 'pisces_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'dramatic change',
                'abandonment',
                'letting go',
                'moving on',
                'discontent',
                'transiton',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'stagnation',
                'fear of change',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [58]
            name: 'Nine of Cups',
            number: '9',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Jupiter',
            planet_icon: 'jupiter_icon.svg',
            astro: 'Pisces',
            astro_icon: 'pisces_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'fulfillment',
                'abundance',
                'satisfaction',
                'prosperity',
                'success',
                'security',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'materialism',
                'arrogance',
                'unfulfillment',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [59]
            name: 'Ten of Cups',
            number: '10',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: 'Water',
            element_icon: 'water_icon.svg',
            planet: 'Mars',
            planet_icon: 'mars_icon.svg',
            astro: 'Pisces',
            astro_icon: 'pisces_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'love',
                'bliss',
                'harmony',
                'family',
                'homecoming',
                'stability',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'disharmony',
                'dysfunction',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [60]
            name: 'Page of Cups',
            number: '11',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: [
                'Water',
                'Earth',
            ],
            element_icon: [
                'water_icon.svg',
                'earth_icon.svg',
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'creativity',
                'idealism',
                'innocence',
                'curiosity',
                'intuition',
                'sensitivity',
                'new insight',
                'good news',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'repression',
                'lack of confidence',
                'immaturity',
                'bad news',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [61]
            name: 'Knight of Cups',
            number: '12',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: [
                'Water',
                'Fire',
            ],
            element_icon: [
                'water_icon.svg',
                'fire_icon.svg',
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Aquarius',
                'Pisces',
            ],
            astro_icon: [
                'aquarius_icon.svg',
                'pisces_icon.svg'
            ],
            up_img: '<upright image URL>',
            up_key: [
                'romance',
                'chivalry',
                'loyalty',
                'charm',
                'peacemaker',
                'unpredictability',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'heartbreak',
                'deception',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [62]
            name: 'Queen of Cups',
            number: '13',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: [
                'Water',
                'Air',
            ],
            element_icon: [
                'water_icon.svg',
                'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Cancer',
                'Gemini',
            ],
            astro_icon: [
                'cancer_icon.svg',
                'gemini_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'compassion',
                'serenity',
                'comfort',
                'nurturing',
                'intuition',
                'dreamer',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'dependent',
                'needy',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [63]
            name: 'King of Cups',
            number: '14',
            suit: 'Cups',
            suit_icon: 'cup_icon.svg',
            element: [
                'Water',
                'Air',
            ],
            element_icon: [
                'water_icon.svg',
                'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Alchemy_air_symbol.svg/2048px-Alchemy_air_symbol.svg.png',
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Scorpio',
                'Libra',
            ],
            astro_icon: [
                'scorpio_icon.svg',
                'libra_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'wisdom',
                'maturity',
                'empathy',
                'diplomacy',
                'balance',
                'creativity',
                'generosity'
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'manipulation',
                'self-centric',
                'overreaction'
            ],
            rev_gen: '<revered description>',
        },


        /////////////   Pentacles   /////////////
        {
            // [64]
            name: 'Ace of Pentacles',
            number: '1',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Taurus',
                'Virgo',
                'Capricorn',
            ],
            astro_icon: [
                'taurus_icon.svg',
                'virgo_icon.svg',
                'capricorn_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'beginnings',
                'prosperity',
                'manifestation',
                'abundance',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'delays',
                'poor planning',
                'financial stress',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [65]
            name: 'Two of Pentacles',
            number: '2',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Jupiter',
            planet_icon: 'jupiter_icon.svg',
            astro: 'Capricorn',
            astro_icon: 'capricorn_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'balance',
                'change',
                'options',
                'adaptability',
                'juggling',
                'flux',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'overextension',
                'fluctuation',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [66]
            name: 'Three of Pentacles',
            number: '3',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Mars',
            planet_icon: 'mars_icon.svg',
            astro: 'Capricorn',
            astro_icon: 'capricorn_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'collaboration',
                'teamwork',
                'apprenticeship',
                'consistent effort',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'competition',
                'lack of teamwork',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [67]
            name: 'Four of Pentacles',
            number: '4',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Sun',
            planet_icon: 'sun_icon.svg',
            astro: 'Capricorn',
            astro_icon: 'capricorn_icon.scg',
            up_img: '<upright image URL>',
            up_key: [
                'frugality',
                'savings',
                'control',
                'scarcity',
                'greed',
                'materialism'
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'overspending',
                'generosity',
                'letting go'
            ],
            rev_gen: '<revered description>',
        },
        {
            // [68]
            name: 'Five of Pentacles',
            number: '5',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Mercury',
            planet_icon: 'mercury_icon.svg',
            astro: 'Taurus',
            astro_icon: 'taurus_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'loss',
                'despair',
                'hardship',
                'poverty',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'recovery',
                'sanctuary',
                'hope',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [69]
            name: 'Six of Pentacles',
            number: '6',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Moon',
            planet_icon: 'moon_icon.svg',
            astro: 'Taurus',
            astro_icon: 'taurus_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'giving',
                'generosity',
                'sharing',
                'charity',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'stinginess',
                'dependence',
                'debt',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [70]
            name: 'Seven of Pentacles',
            number: '7',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Saturn',
            planet_icon: 'saturn_icon.svg',
            astro: 'Taurus',
            astro_icon: 'taurus_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'patience',
                'perserverance',
                'steady growth',
                'long-term rewards',
                'harvest',
                'fruition',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'lack of planning',
                'frustration',
                'laziness',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [71]
            name: 'Eight of Pentacles',
            number: '8',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Sun',
            planet_icon: 'sun_icon.svg',
            astro: 'Virgo',
            astro_icon: 'virgo_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'practice',
                'skill',
                'discipline',
                'craftsmanship',
                'mastery',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'self-improvement',
                'perfectionism',
                'shoddy work',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [72]
            name: 'Nine of Pentacles',
            number: '9',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Venus',
            planet_icon: 'venus_icon.svg',
            astro: 'Virgo',
            astro_icon: 'virgo_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'abundance',
                'luxury',
                'indulgence',
                'accomplishment',
                'refinery',
                'success',
                'financial independence',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'self-worth',
                'overworked',
                'materialism',
                'envy',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [73]
            name: 'Ten of Pentacles',
            number: '10',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            planet: 'Mercury',
            planet_icon: 'mercury_icon.svg',
            astro: 'Virgo',
            astro_icon: 'virgo_icon.svg',
            up_img: '<upright image URL>',
            up_key: [
                'financial security',
                'legacy',
                'inheritance',
                'family',
                'privilege',
                'foundations',
                'success',
                'the good life',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'financial loss',
                'family discord',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [74]
            name: 'Page of Pentacles',
            number: '11',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            // astro: '<insert astro>',
            // astro_icon: '<astro icon URL>',
            up_img: '<upright image URL>',
            up_key: [
                'ambition',
                'manifestation',
                'study',
                'good news',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'procrastination',
                'immaturity',
                'laziness',
                'bad news',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [75]
            name: 'Knight of Pentacles',
            number: '12',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: [
                'Earth',
                'Fire',
            ],
            element_icon: [
                'earth_icon.svg',
                'fire_icon.svg',
            ],
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Virgo',
                'Leo',
            ],
            astro_icon: [
                'virgo_icon.svg',
                'leo_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'hard work',
                'methodic',
                'productivity',
                'grounded',
                'dependable',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'perfectionism',
                'boredom',
                'laziness',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [76]
            name: 'Queen of Pentacles',
            number: '13',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Capricorn',
                'Sagittarius',
            ],
            astro_icon: [
                'capricorn_icon.svg',
                'sagittarius_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'grounded',
                'practical',
                'generosity',
                'prosperity',
                'nurturing',
                'maternal',
                'fertility',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'ungrounded',
                'disorganization',
                'materialism',
                'greed',
                'jealousy',
                'barrenness',
            ],
            rev_gen: '<revered description>',
        },
        {
            // [77]
            name: 'King of Pentacles',
            number: '14',
            suit: 'Pentacles',
            suit_icon: 'pentacle_icon.svg',
            element: 'Earth',
            element_icon: 'earth_icon.svg',
            // planet: '<insert planet>',
            // planet_icon: '<planet icon URL>',
            astro: [
                'Taurus',
                'Aries'
            ],
            astro_icon: [
                'taurus_icon.svg',
                'aries_icon.svg',
            ],
            up_img: '<upright image URL>',
            up_key: [
                'prosperity',
                'security',
                'ambition',
                'paternal',
                'hardworking',
                'grounded',
            ],
            up_gen: '<upright description>',
            rev_img: '<reversed image URL>',
            rev_key: [
                'critical',
                'harsh',
                'stinginess',
                'materialism',
            ],
            rev_gen: '<revered description>',
        },
    ]
    await Card.insertMany(cards)
    console.log('Inserted cards')
}

const run = async() => {
    await main()
    db.close()
}
  
run()